//! Stamps `x-engine-build.xon` beside the engine.
//!
//! Word size, byte order, os and arch are facts of a BUILD, not of a source
//! tree: the same repository yields a 32-bit and a 64-bit engine whose ISA and
//! layout digests are identical. So they are not in `x-engine.xon` — x-lang's
//! generator deliberately refuses to guess them — and they are stamped here
//! instead, where the answer is known.
//!
//! Taken from the TARGET, never from the host. `CARGO_CFG_TARGET_*` describes
//! what is being built, so a cross-compiled engine is stamped with the machine
//! it will RUN on rather than the one it was compiled on. Reading `size_of` in
//! this file would have described the build machine and been silently wrong in
//! exactly the case the stamp exists for.
//!
//! These are PARAMETERS, not capabilities: an engine reports them, and nothing
//! may require a particular value. x-lang's contract gate refuses a parameter in
//! a requirements list, which is the rule this file is on the other end of.

use std::io::Write;

fn main() {
    let dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let path = std::path::Path::new(&dir).join("x-engine-build.xon");

    let bits: u32 = std::env::var("CARGO_CFG_TARGET_POINTER_WIDTH")
        .unwrap_or_default()
        .parse()
        .unwrap_or(0);
    let endian = std::env::var("CARGO_CFG_TARGET_ENDIAN").unwrap_or_default();
    let os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let triple = std::env::var("TARGET").unwrap_or_default();

    // Anything the compiler did not tell us is written as `unknown`, which the
    // consumers skip. A guessed value would be indistinguishable from a measured
    // one at the point it mattered.
    let unknown = |s: &str| {
        if s.is_empty() {
            "unknown".to_string()
        } else {
            s.to_string()
        }
    };

    // x-lang'"'"'S SPELLINGS, not Rust'"'"'s. The parameter VALUES are part of the
    // contract, not free text: tests/x/conformance/posix/foreign.spec.md compares
    // %param-os against the literal `darwin` and %param-arch against `arm64`,
    // `x86-64` and `i386`, and x-lang'"'"'s tools/contract/features.x names the same
    // set beside its (os) and (arch) parameter rows.
    //
    // Rust'"'"'s target names differ for the same machines -- macos, aarch64, x86_64
    // -- so an engine stamping them verbatim reports true facts in a vocabulary
    // nothing can read, and every comparison against a literal quietly fails. It
    // translates rather than asserting its own words, because an engine choosing
    // the terms it is judged by is the thing this whole contract is arranged to
    // prevent.
    let os = match os.as_str() {
        "macos" => "darwin".to_string(),
        other => other.to_string(),
    };
    let arch = match arch.as_str() {
        "aarch64" => "arm64".to_string(),
        "x86_64" => "x86-64".to_string(),
        "x86" => "i386".to_string(),
        other => other.to_string(),
    };

    let mut out = String::new();
    out.push_str("; x-engine-build.xon -- generated by build.rs; do not edit\n");
    out.push_str(";\n");
    out.push_str("; Facts of THIS BUILD, taken from the target the compiler was aimed at.\n");
    out.push_str("; Parameters are reported, never required.\n");
    out.push_str(&format!("(param machine \"{}\")\n", triple));
    out.push_str(&format!(
        "(param word-size {})\n",
        if bits > 0 {
            (bits / 8).to_string()
        } else {
            "unknown".into()
        }
    ));
    out.push_str(&format!("(param endian {})\n", unknown(&endian)));
    out.push_str(&format!("(param os {})\n", unknown(&os)));
    out.push_str(&format!("(param arch {})\n", unknown(&arch)));

    if let Ok(mut f) = std::fs::File::create(path) {
        let _ = f.write_all(out.as_bytes());
    }
    println!("cargo:rerun-if-changed=build.rs");
}
