; tools/contract/claims.x -- what x-engine-rust ASSERTS about itself.
;
; x-engine.xon is generated by x-lang's tools/contract/gen-engine-xon.sh, and most
; of it is DERIVED from tools/contract/isa.x.  Two kinds of row cannot be derived
; and live here: GUARANTEES (behaviours, mostly things this engine does not do)
; and NON-ISA CAPABILITIES (the wrapper protocol, which the instruction manifest
; does not describe).
;
; Every atom below must exist in x-lang's tools/contract/features.x.  A typo is
; caught there, not tolerated here.
;
; CLAIM LESS RATHER THAN MORE.  Under-declaring costs capability; over-declaring
; costs correctness, and x-lang's compliance suite exists to catch exactly that.
; Rows appear here as the engine earns them.

(def %claims (lit (
  ; What this engine is called.  x-lang's generator used to take the name from
  ; the DIRECTORY it found an engine in, which is where an engine happens to sit
  ; rather than who it is: a checkout sits in `x-engine-rust` and an unpacked
  ; release sits in `x-engine-rust-<release>-<os>-<arch>`, and a project whose
  ; pin.xon says (engine "x-engine-rust") would have been refused for the shape
  ; of a path.  Asserted here for the same reason the binary's name is.
  (name "x-engine-rust")

  ; The binary this engine builds.  x.sh reads this row to learn what to run, so
  ; an engine that does not produce a file called x-bin still installs and starts.
  (binary "x-engine")

  ; --- guarantees ---
  ; Two of these are free, and saying why is more useful than asserting them.
  ; This engine has NO COLLECTOR: the `core` profile does not include isa/gc, so
  ; the smallest thing that can boot x-lang allocates into a growing arena and
  ; never frees.  Allocation therefore cannot collect, and a live object cannot
  ; move -- not because the collector is careful, but because there is none.  If
  ; a collector is ever added, both rows stop being free and must be re-earned.
  (guarantee gc/explicit-only)
  (guarantee gc/non-moving)
  ; The fixnum and the arena offset are both a machine word.
  (guarantee int/ptr-same-width)

  ; Proper tail calls, unbounded depth.  EARNED, not free: this engine recursed
  ; on the Rust stack and died between five and ten thousand frames until the
  ; evaluator grew a trampoline.  A form in tail position is parked and picked
  ; up by the eval loop rather than evaluated under a new frame -- the reference
  ; engine parks it in the base's tco-expr and tco-env slots for the same
  ; reason.  A million tail calls now run flat.
  (guarantee eval/tco)

  ; --- capabilities that are not instruction groups ---
  ; These cannot be derived from isa.x: they are build switches and protocol
  ; promises, so the engine states them and x-lang's compliance suite is what
  ; falsifies them.

  ; Contract layer E, all three parts, each verified by RUNNING the engine
  ; rather than by reading it.
  (provides invoke/pipe-stdin)   ; the program arrives on stdin and is read-eval'd
  (provides invoke/argv)         ; every argv element is bound as the `args` list;
                                 ;   the engine parses NOTHING -- it does not know
                                 ;   what --batch or --quiet mean
  (provides err/stderr-prefix)   ; diagnostics on STDERR, prefixed `*** ERROR: `,
                                 ;   and stdout left untouched

  (provides io/include)          ; the `include` primitive; repo-mode boot cannot
                                 ;   start without it

  ; Ships tools/contract/obj-layout.x and tools/contract/base-paths.x -- BOTH the
  ; files lib/x/boot/engine.x includes, which is what this capability is for.
  ;
  ; x-lang's features.x describes it as three files, naming base-layout.x as well.
  ; That file is the C engine's own generator input: gen-base-layout.awk turns it
  ; into C accessors, and nothing in lib/ includes it.  Shipping one here would be
  ; producing an artefact for a compiler this engine does not use, so the claim is
  ; made against what the library actually reaches.
  (provides reflect/layout-data)

  ; int <-> ptr round-trips faithfully enough to size a word, which is how
  ; lib/x/boot/data.x probes the width at boot.  Free here for the same reason
  ; int/ptr-same-width is: a pointer IS an arena offset, so the round trip is a
  ; re-tagging rather than a conversion.
  (provides reflect/word-probe)
)))
